In [1]:
# 1. You are given two strings s and t. String t is generated by randomly shuffling string s and then adding one more letter at 
# a random position. Return the letter that was added to t.
# Examples:
# find_the_difference("abcd", "abcde") ➞ "e"
# find_the_difference("", "y") ➞ "y"
# find_the_difference("ae", "aea") ➞ "a"

# Sol :

def find_the_difference(s1, s2):
    try:
        s1 = list(s1)
        s2 = list(s2)
        if len(s1) > len(s2):
            for i in set(s1):
                if s1.count(i) != s2.count(i):
                    return i
        else:
            for i in set(s2):
                if s1.count(i) != s2.count(i):
                    return i
    except Exception as e:
        return e

In [2]:
find_the_difference("abcd", "abcde")

'e'

In [3]:
find_the_difference("", "y")

'y'

In [4]:
find_the_difference("ae", "aea")

'a'

In [5]:
# 2. Given a function that accepts unlimited arguments, check and count how many data types are in those arguments. Finally 
#    return the total in a list.
#    List order is: [int, str, bool, list, tuple, dictionary]
#    Examples:
#    count_datatypes(1, 45, "Hi", False) ➞ [2, 1, 1, 0, 0, 0]
#    count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1) ➞ [3, 0, 0, 1, 1, 0]
#    count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)
#            ➞ [2, 2, 3, 1, 0, 2]
#    count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6]) ➞ [2, 0, 1, 2, 2, 0]

# Sol :
from collections import OrderedDict
def count_datatypes(*args):
    try:
        output=OrderedDict({"int" : 0, 'str' : 0, 'bool' : 0, 'list' : 0, 'tuple' : 0, 'dict' : 0})
        for i in args:
            output[(type(i).__name__)] += 1
        return list(output.values())
    except Exception as e:
        return e

In [6]:
count_datatypes(1, 45, "Hi", False)

[2, 1, 1, 0, 0, 0]

In [7]:
count_datatypes([10, 20], ("t", "Ok"), 2, 3, 1)

[3, 0, 0, 1, 1, 0]

In [8]:
 count_datatypes("Hello", "Bye", True, True, False, {"1": "One", "2": "Two"}, [1, 3], {"Brayan": 18}, 25, 23)

[2, 2, 3, 1, 0, 2]

In [9]:
count_datatypes(4, 21, ("ES", "EN"), ("a", "b"), False, [1, 2, 3], [4, 5, 6])

[2, 0, 1, 2, 2, 0]

In [10]:
# 3. A Fibonacci string is a precedence of the Fibonacci series. It works with any two characters of the English alphabet
#    (as opposed to the numbers 0 and 1 in the Fibonacci series) as the initial items and concatenates them together as it 
#    progresses in a similar fashion as the Fibonacci series.
#    Examples:
#    fib_str(3, ["j", "h"]) ➞ "j, h, hj"
#    fib_str(5, ["e", "a"]) ➞ "e, a, ae, aea, aeaae"
#    fib_str(6, ["n", "k"]) ➞ "n, k, kn, knk, knkkn, knkknknk"

In [11]:
def fib_str(num, lst):
    try:
        output = lst
        if num > 2:
            for i in range(2, num):
                output.append(lst[-1] + lst[-2])
        return output
    except Exception as e:
        return e

In [12]:
fib_str(3, ["j", "h"])

['j', 'h', 'hj']

In [13]:
fib_str(5, ["e", "a"])

['e', 'a', 'ae', 'aea', 'aeaae']

In [14]:
fib_str(6, ["n", "k"])

['n', 'k', 'kn', 'knk', 'knkkn', 'knkknknk']

In [15]:
# 4. Given an integer between 0 and 26, make a variable (self.answer). That variable would be assigned to a string in this 
#    format:
#    "nines:your answer, threes:your answer, ones:your answer"
#    You need to find out how many ones, threes, and nines it would at least take for the number of each to add up to the given
#    integer when multiplied by one, three or nine (depends).
#    Examples:
#       ones_threes_nines(10) ➞ "nines:1, threes:0, ones:1"
#       ones_threes_nines(15) ➞ "nines:1, threes:2, ones:0"
#       ones_threes_nines(22) ➞ "nines:2, threes:1, ones:1"

# Sol :

def ones_threes_nines(num):
    try:
        pass
    except Exception as e:
        return e

In [16]:
def ones_threes_nines(num):
    output = {'nines' : 0, 'threes' : 0, 'ones' : 0}
    input_num = num
    while input_num > 0:
        if input_num >= 9:
            input_num -= 9
            output['nines'] += 1
        elif input_num >= 3:
            input_num -= 3
            output['threes'] += 1
        elif input_num >= 1:
            input_num -= 1
            output['ones'] += 1
    return f"nines : {output['nines']}, threes : {output['threes']}, ones : {output['ones']}"

In [17]:
ones_threes_nines(10)

'nines : 1, threes : 0, ones : 1'

In [18]:
ones_threes_nines(15)

'nines : 1, threes : 2, ones : 0'

In [19]:
ones_threes_nines(22)

'nines : 2, threes : 1, ones : 1'

In [20]:
# 5. The Fibonacci sequence is a classic use case for recursive functions since the value of the sequence at a given index is 
#    dependent on the sum of the last two values. However, the recursion tree created by solving the Fibonacci sequence recursively 
#    can grow quite fast. Therefore it can be important to think about the implications of running a function recursively. 
#    Depending on the size of n needed and the capabilities of the system in question you might want to take a different approach.
#    Write a non-recursive function that takes an integer n and returns the Fibonacci sequence's value at index n.
#    Examples:
#    fib(6) ➞ 8
#    0 + 1 = 1, 1 + 1 = 2, 1 + 2 = 3, 2 + 3 = 5, 3 + 5 = 8
#    fib(1) ➞ 1
#    fib(2) ➞ 1

def fib(num):
    try:
        if num < 1:
            return 'Minimum two digits are required to do the fibnocci series'
        else:
            output = [0, 1]
            for i in range(2, num+1):
                output.append(output[-1] + output[-2])
            return output[-1]
    except Exception as e:
        return e

In [21]:
fib(6)

8

In [22]:
fib(1)

1

In [23]:
fib(2)

1